### ISSUE TITLE
Can't play video

### ISSUE THREAD

**Issue by EdgardoMartin** [dularion/streama-app#6]
Every time I try to play a video it tells me that the format is incompatible. I have tried with webm, mp4 and mkv. Even with "ffmpeg -i input.mkv -vcodec h264 -acodec aac -strict -2 output.mp4" as indicated by the guide and nothing. Any help on what would be the correct format? Thank you very much.

![error-streama-app](https://user-images.githubusercontent.com/33255132/32223754-6d14f316-be1d-11e7-83f3-3764ceb39992.png)

**Comment by dularion** [comment]
I've added a wrapper now which should make more videos compatible. Please try the newest release (v0.0.6)

**Comment by EdgardoMartin** [comment]
I updated and it works, thanks
